ARG BASE_REPO="prymalinstynct"
ARG BASE_IMAGE="kasm-rhel-9"
ARG BASE_TAG="base-dev"
FROM $BASE_REPO/$BASE_IMAGE:$BASE_TAG

USER root

ENV DISTRO=rhel9
ENV HOME=/home/kasm-default-profile
ENV STARTUPDIR=/dockerstartup
WORKDIR $HOME

### Envrionment config
ENV SKIP_CLEAN=true \
    KASM_RX_HOME=$STARTUPDIR/kasmrx \
    DONT_PROMPT_WSL_INSTALL="No_Prompt_please" \
    INST_DIR=$STARTUPDIR/install \
    INST_SCRIPTS="/rhel9/install/tools/install_tools_deluxe.sh \
                  /rhel9/install/misc/install_tools.sh \
                  /rhel9/install/chromium/install_chromium.sh \
                  /rhel9/install/firefox/install_firefox.sh \
                  /rhel9/install/sublime_text/install_sublime_text.sh \
                  /rhel9/install/vs_code/install_vs_code.sh \
                  /rhel9/install/remmina/install_remmina.sh \
                  /rhel9/install/only_office/install_only_office.sh \
                  /rhel9/install/gimp/install_gimp.sh \
                  /rhel9/install/ansible/install_ansible.sh \
                  /rhel9/install/terraform/install_terraform.sh \
                  /rhel9/install/thunderbird/install_thunderbird.sh \
                  /rhel9/install/cleanup/cleanup.sh \
                  /rhel9/install/cleanup/deep-clean.sh"

# Copy install scripts
COPY ./src/ $INST_DIR

# Run installations
RUN \
  for SCRIPT in $INST_SCRIPTS; do \
    bash ${INST_DIR}${SCRIPT} || exit 1; \
  done && \
  $STARTUPDIR/set_user_permission.sh $HOME && \
  rm -f /etc/X11/xinit/Xclients && \
  chown 1000:0 $HOME && \
  mkdir -p /home/kasm-user && \
  chown -R 1000:0 /home/kasm-user && \
  rm -Rf ${INST_DIR}

# Userspace Runtime
ENV HOME=/home/kasm-user
WORKDIR $HOME
USER 1000

CMD ["--tail-log"]
