name: Build of UBI 9 based Developer Images

on:
  push:
    branches: [ main ]

  workflow_call:
    # Map the workflow outputs to job outputs
    secrets:
      REDHAT_USERNAME:
        required: true
      REDHAT_PASSWORD:
        required: true
    outputs:
      uniq_tag:
        description: "The first output string"
        value: ${{ jobs.build_universal_ubi9_image.outputs.output1 }}

jobs:
  build-base-image:
    name: Build base image
    strategy:
      fail-fast: false
      matrix:
        runners: ['ubuntu-22.04', 'ubuntu-22.04-arm']
    runs-on: ${{matrix.runners}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set arch environment variable
        run: |
          if [[ ${{matrix.runners}} == 'ubuntu-22.04' ]]; then
            echo arch="amd64" >> $GITHUB_ENV
          else
            echo arch="arm64" >> $GITHUB_ENV
          fi
      - name: Set short_sha environment variable
        run: echo short_sha="$(git rev-parse --short=7 HEAD)" >> $GITHUB_ENV
      - name: Free runner space
        run: sudo rm -rf /usr/local/lib/android
      - name: Cleanup docker images
        run: docker system prune -af
      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: registry.redhat.io
          username: ${{ secrets.REDHAT_USERNAME }}
          password: ${{ secrets.REDHAT_PASSWORD }}
      - name: Build base image
        run: |
          cd base/ubi9 && docker buildx build \
          --platform linux/${{env.arch}} \
          --progress=plain \
          --push \
          -t quay.io/devfile/base-developer-image:${{env.arch}}-${{env.short_sha}} .